import { getLangDir } from "rtl-detect";
import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./../globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { cn } from "@/lib/utils";

const cairo = Cairo({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  const direction = getLangDir(locale);
  const messages = await getMessages();
  return (
    <html lang={locale} dir={direction} data-theme="cupcake">
      <body className={cn("", cairo.className)}>
        <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
